apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sent-marketing
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: ""
    traefik.ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/ssl-permanent-redirect: "true"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/connection-proxy: "true"
    cert-manager.io/cluster-issuer: "acme"
spec:
  rules:
    - host: dev.sent.dm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sent-marketing
                port:
                  number: 3000
  tls:
    - hosts:
        - dev.sent.dm
      secretName: dev.sent.dm-tls